version: "3.5"

services:
  acme-backend:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:mariadb://host.docker.internal:3306/testshop
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=
    ports:
      - 8080:8080
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge